# Generated by Django 6.0.5 on 2026-08-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.CharField(blank=True, help_text='Example: catalog/images/products/myimage.jpg', max_length=255),
        ),
    ]
